base_url_dc_1 : 'https://anyurl.com/contextpath/component/'
base_url_dc_2 : 'https://anyurl2.com/contextpath2/component/'

componentCodes : 'PathParameter'

username : 'USERNAME'
password : 'PASSWORD'

headers : '{"filter-time-stamp": "2018-01-01T11:00:13-0400", "Accept-Encoding": "gzip"}'
